- id: '1570558248746' 
  alias: living_room_bulb_temp
  description: Olohuoneen värilämpötilan säätö
  # Vaihdetaan olohuoneen värilämpötilaa silloin, kun input_numberia säädetään.
  trigger:
    platform: state
    entity_id: input_number.b1_temp
  condition: # Toteutetaan vain, jos lamppu on päällä, jottei lamppu mene päälle värilämpötilasäädön takia.
  - condition: state
    entity_id: light.tradfri_bulb
    state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: # Kummatkin olohuoneen lamput
      - light.tradfri_bulb
      - light.tradfri_bulb_2
      color_temp: '{{ states.input_number.b1_temp.state | int }}'
      transition: 1 # Sekunnin siirtymä

- id: '1570783783314'
  alias: kitchen_temp_adj
  description: Olohuoneen värilämpötilan säätö keittiön mukaan
  # Aktivoituu, kun keittiön valo sytytetään. Olohuoneen värilämpötila vaihtuu 4000 K.
  trigger:
  - device_id: 7d6e6f5c533448ee9c82544a8cec7c25
    domain: light
    entity_id: light.tradfri_driver
    platform: device
    type: turned_on
  condition: # Niin ikään toteutetaan vain, jos valo on jo päällä.
    condition: state
    entity_id: light.tradfri_bulb
    state: "on"
  action: 
  - service: input_number.set_value # Tallennetaan ensin nykyinen värilämpötila
    data_template:
      entity_id: input_number.b1_temp
      value: '{{ states.light.tradfri_bulb.attributes.color_temp | int }}'
  - service: light.turn_on # Vaihdetaan värilämpötila.
    data: 
      entity_id: 
      - light.tradfri_bulb
      - light.tradfri_bulb_2
      kelvin: 4000
      transition: 1
    

- id: '1570794048621'
  alias: kicthen_light_temp_off
  # Edellinen käänteisesti
  description: Säädä olohuoneen valoja sammutettaessa keittiön valot
  trigger:
  - device_id: 7d6e6f5c533448ee9c82544a8cec7c25
    domain: light
    entity_id: light.tradfri_driver
    platform: device
    type: turned_off
  condition:
    condition: state
    entity_id: light.tradfri_bulb
    state: "on"
  action:
    data_template:
      color_temp: '{{ states.input_number.b1_temp.state | int }}'
      entity_id: 
      - light.tradfri_bulb
      - light.tradfri_bulb_2
      transition: 1
    service: light.turn_on

- id: "1570794048622"
  alias: "kitchen_living_bulb_temp_3"
  description: Säädä olohuoneen valojen värilämpötila sytytettäessä ne, jos keittiön valo päällä
  trigger: # Sytytettäessä olohuoneen valot
  - entity_id: 
    - light.tradfri_bulb
    - light.tradfri_bulb_2
    platform: state
    to: "on"
  condition: # Jos keittiön valot päällä
    condition: state
    entity_id: light.tradfri_driver
    state: "on"
  action: 
  - service: input_number.set_value # Tallennetaan ensin nykyinen värilämpötila
    data_template:
      entity_id: input_number.b1_temp
      value: '{{ states.light.tradfri_bulb.attributes.color_temp | int }}'
  - service: light.turn_on # Säädetään värilämpötila
    data:
      kelvin: 4000
      entity_id:
      - light.tradfri_bulb
      - light.tradfri_bulb_2

- id: "1"
  alias: "hall_twilighttime_dim"
  description: "Pienentää eteisen valon kirkkautta iltaisin, jos olohuoneen valot eivät ole päällä"
  trigger: # Aktivoituu, kun eteisen valo syttyy
  - entity_id: light.tradfri_bulb_5
    platform: state
    to: "on"
  condition: # Edellyttää, että olohuoneessa ei valoja ja tapahtuu pimeän aikaan
  - condition: "state"
    entity_id: light.tradfri_bulb
    state: "off"
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < -6 }}' # Katsotaan auringon korkeudesta, koska aktivoituu.
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") > -18 }}'
  action: # Laitetaan valo 30 % teholle. Värilämpötila 4000 K
  - service: light.turn_on
    data:
      brightness: 76 
      entity_id: light.tradfri_bulb_5
      transition: 1
  - service: light.turn_on
    data:
      kelvin: 4000
      entity_id: light.tradfri_bulb_5
      transition: 1

- alias: "hall_nighttime_dim"
  description: "Pienentää eteisen valon kirkkautta öisin, jos olohuoneen valot eivät ole päällä"
  trigger: # Aktivoituu, kun eteisen valo syttyy
  - entity_id: light.tradfri_bulb_5
    platform: state
    to: "on"
  condition: # Edellyttää, että olohuoneessa ei valoja ja tapahtuu pimeän aikaan
  - condition: "state"
    entity_id: light.tradfri_bulb
    state: "off"
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") <= 18 }}' # Katsotaan auringon korkeudesta, koska aktivoituu.
  action: # Laitetaan valo 1% teholle. Keltaisin värilämpötila.
  - service: light.turn_on
    data:
      brightness: 1 
      entity_id: light.tradfri_bulb_5
      transition: 1
  - service: light.turn_on
    data:
      color_temp: 450
      entity_id: light.tradfri_bulb_5
      transition: 1

- id: "2"
  alias: "hall_non_dimming"
  description: "Pitää huolen, että eteisessä ei ole himmennystä päivällä"
  trigger: #Aktivoituu, kun eteisen valo syttyy
  - entity_id: light.tradfri_bulb_5
    platform: state
    to: "on"
  condition: # Suoritetaan vain, jos olohuoneen valo on pois päältä ja aurinko on riittävän ylhääläl
  - condition: "state"
    entity_id: light.tradfri_bulb
    state: "off"
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") > -6 }}' # Katsotaan auringon korkeudesta, koska aktivoituu.
  action: # Laitetaan valo 100 % teholle. Värilämpötila 4000 K
  - service: light.turn_on
    data:
      brightness: 254
      entity_id: light.tradfri_bulb_5
      transition: 1
  - service: light.turn_on
    data: 
      kelvin: 4000
      entity_id: light.tradfri_bulb_5
      transition: 1

- id: "3"
  alias: "hall_dimming_based_on_living_room"
  description: "Laittaa eteiseen saman kirkkauden kuin olohuoneessa, jos valo päällä"
  trigger: # Aktivoituu, kun eteisen valo syttyy
  - entity_id: light.tradfri_bulb_5
    platform: state
    to: "on"
  condition: # Suoritetaan vain, jos olohuoneen valo on päällä
  - condition: "state"
    entity_id: light.tradfri_bulb
    state: "on"
  action: # Laitetaan valo samalle teholle ja värilämpotilalle
  - service: light.turn_on
    data_template:
      brightness: '{{ states.light.tradfri_bulb.attributes.brightness | int }}'
      entity_id: light.tradfri_bulb_5
      transition: 1
  - delay: "00:00:01"
  - service: light.turn_on
    data_template:
      color_temp: '{{ states.light.tradfri_bulb.attributes.color_temp | int }}'
      entity_id: light.tradfri_bulb_5
      transition: 1

- id: "4"
  alias: "hall_dimming_based_on_living_room_dimming"
  description: Muuttaa eteisen kirkkautta, kun olohuoneen kirkkautta / värilämpötilaa muutetaan.
  trigger: # Aktivoituu, kun olohuoneen valoa säädetään
  - entity_id: light.tradfri_bulb
    platform: state
  condition: # Vain kun eteisen valo on päällä, jottei sitä sytytetä tämän takia.
  - condition: state
    entity_id: light.tradfri_bulb_5
    state: "on"
  action: # Valo samalle teholle ja värilämpötilalle
  - service: light.turn_on
    data_template:
      brightness: '{{ states.light.tradfri_bulb.attributes.brightness | int }}'
      entity_id: light.tradfri_bulb_5
      transition: 1
  - service: light.turn_on
    data_template:
      color_temp: '{{ states.light.tradfri_bulb.attributes.color_temp | int }}'
      entity_id: light.tradfri_bulb_5
      transition: 1

- id: '15705582487321' 
  alias: living_room_bulb_bright
  description: Olohuoneen kirkkauden säätö
  # Vaihdetaan olohuoneen valojen kirkkautta silloin, kun input_numberia säädetään.
  trigger:
    platform: state
    entity_id: input_number.b1_bright
  condition: # Toteutetaan vain, jos lamppu on päällä, jottei lamppu mene päälle turhaan.
  - condition: state
    entity_id: light.tradfri_bulb
    state: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: # Kummatkin olohuoneen lamput
      - light.tradfri_bulb
      - light.tradfri_bulb_2
      brightness: '{{ states.input_number.b1_bright.state | int }}'
      transition: 1 # Sekunnin siirtymä

- alias: living_room_bulb_bright_2
  description: Input_numberin säätö olohuoneen valojen kirkkauden mukaan
  # Vaihdetaan olohuoneen valojen kirkkautta silloin, kun input_numberia säädetään.
  trigger: # Aina, kun valoa säädetään jotenkin.
    platform: state
    entity_id: light.tradfri_bulb
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.b1_bright
      value: '{{ states.light.tradfri_bulb.attributes.brightness | int }}'


- id: '5' # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa aamulla
  alias: Enable first morning trigger
  hide_entity: true
  trigger:
    platform: time
    at: '05:00:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.first_morning

- id: '6'
  alias: Disable first morning
  trigger:
    platform: time
    at: '10:00:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.first_morning

- id: '7'
  alias: First morning # Valojen aamutilan sytytys
  trigger: # Sytytettäessä olohuoneen valot
    platform: state
    entity_id: 
    - light.tradfri_bulb
    - light.tradfri_bulb_2
    from: "off" # Tämä ei liene välttämätön rivi.
    to: "on"
  condition: # Vain, jos on aamun ensimmäinen
    condition: state
    entity_id: input_boolean.first_morning
    state: 'on'
  action:
  - service: input_boolean.turn_off # Laitetaan "odotusmuuttuja" pois, jotta tapahtuu vain kerran aamussa. 
    entity_id: input_boolean.first_morning
  - service: script.turn_on # Aktivoidaan valmis, erillinen aamuprofiiliskripti.
    entity_id: script.morning

- alias: Enable first daytime trigger  # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa päivällä
  hide_entity: true
  trigger:
    platform: time
    at: '10:00:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.first_daytime

- alias: Disable first daytime  # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa päivällä
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.first_daytime

- id: '8'
  alias: First daytime # Valojen päivätilan sytytys
  trigger: # Sytytettäessä olohuoneen valot
    platform: state
    entity_id: 
    - light.tradfri_bulb
    - light.tradfri_bulb_2
    from: "off" # Tämä ei liene välttämätön rivi.
    to: "on"
  condition: # Vain, jos on päivän ensimmäinen
    condition: state
    entity_id: input_boolean.first_daytime
    state: 'on'
  action:
  - service: input_boolean.turn_off # Laitetaan "odotusmuuttuja" pois, jotta tapahtuu vain kerran aamussa. 
    entity_id: input_boolean.first_daytime
  - service: script.turn_on # Aktivoidaan valmis, erillinen aamuprofiiliskripti.
    entity_id: script.daytime

- alias: Enable first daytime trigger  # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa illalla
  hide_entity: true
  trigger:
    platform: time
    at: '18:00:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.first_evening

- alias: Disable first daytime  # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa illalla
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.first_evening

- id: '9'
  alias: First evening # Valojen iltatilan sytytys
  trigger: # Sytytettäessä olohuoneen valot
    platform: state
    entity_id: 
    - light.tradfri_bulb
    - light.tradfri_bulb_2
    from: "off" # Tämä ei liene välttämätön rivi.
    to: "on"
  condition: # Vain, jos on aamun ensimmäinen
    condition: state
    entity_id: input_boolean.first_evening
    state: 'on'
  action:
  - service: input_boolean.turn_off # Laitetaan "odotusmuuttuja" pois, jotta tapahtuu vain kerran aamussa. 
    entity_id: input_boolean.first_evening
  - service: script.turn_on # Aktivoidaan valmis, erillinen aamuprofiiliskripti.
    entity_id: script.evening
  
- alias: Enable first night trigger  # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa yöllä
  hide_entity: true
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.first_night

- alias: Disable first daytime  # Käytetään selvittämään, laitetaanko lamput päälle ensimmäistä kertaa yöllä
  trigger:
    platform: time
    at: '5:00:00'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.first_night

- id: '10'
  alias: First night # Valojen sytytys elokuvatilaan öisin.
  trigger: # Sytytettäessä olohuoneen valot
    platform: state
    entity_id: 
    - light.tradfri_bulb
    - light.tradfri_bulb_2
    from: "off" # Tämä ei liene välttämätön rivi.
    to: "on"
  condition: # Vain, jos on aamun ensimmäinen
    condition: state
    entity_id: input_boolean.first_night
    state: 'on'
  action:
  - service: input_boolean.turn_off # Laitetaan "odotusmuuttuja" pois, jotta tapahtuu vain kerran aamussa. 
    entity_id: input_boolean.first_night
  - service: script.turn_on # Aktivoidaan valmis, erillinen aamuprofiiliskripti.
    entity_id: script.movie