
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8
group: !include group.yaml
homeassistant:
   whitelist_external_dirs:
    - '/config'

# DNS:

http:
  base_url: “https://halminen.duckdns.org:8123”
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem 
  ip_ban_enabled: true
  login_attempts_threshold: 3 
  
