
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tradfri:
  host: 192.168.1.192
tts:
  - platform: google_translate
lovelace: 
  mode: yaml

# Includet:
automation: !include automations.yaml
script: !include scripts.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
scene: !include scene.yaml
group: !include group.yaml
sensor: !include sensor.yaml
light: !include light.yaml
homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/config'

# Simple push
notify:
  - name: simplepush
    platform: simplepush
    device_key: K4jZhB