- platform: group
  name: livingroom
  entities:
    - light.tradfri_bulb
    - light.tradfri_bulb_2

- platform: group
  name: bedroom
  entities:
    - light.tradfri_bulb_4
    - light.tradfri_bulb_3
    