- platform: file
  name: sauna_temperature
  file_path: custom_components/ruuvitag-sensor/tag1.json
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: "°C"
  scan_interval: 1

- platform: file
  name: sauna_humidity
  file_path: custom_components/ruuvitag-sensor/tag1.json
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: "%"
  scan_interval: 1

- platform: file
  name: sauna_pressure
  file_path: custom_components/ruuvitag-sensor/tag1.json
  value_template: '{{ value_json.pressure }}'
  unit_of_measurement: "hPa"
  scan_interval: 1

- platform: file
  name: outside_temperature
  file_path: custom_components/ruuvitag-sensor/tag2.json
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: "°C"
  scan_interval: 1

- platform: file
  name: outside_humidity
  file_path: custom_components/ruuvitag-sensor/tag2.json
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: "%"
  scan_interval: 1

- platform: file
  name: outside_pressure
  file_path: custom_components/ruuvitag-sensor/tag2.json
  value_template: '{{ value_json.pressure }}'
  unit_of_measurement: "hPa"
  scan_interval: 1

- platform: template
  sensors:
      outside_saturation_pressure:
        unit_of_measurement: "hPa"
        value_template: >-
          {% set A = 6.116441 | float %}
          {% set m = 7.591386 | float %}
          {% set tn = 240.7263 | float %}
          {% set t = states('sensor.outside_temperature') | float %}
          {{ A * 10 ** ((m*t)/(t+tn))}}
    
- platform: template
  sensors:
      outside_dewpoint:
        unit_of_measurement: "°C"
        value_template: >-
          {% set rh = states('sensor.outside_humidity') | float %}
          {% set pw = states('sensor.outside_saturation_pressure') * rh / 100 | float %}
          {% set A = 6.116441 | float %}
          {% set m = 7.591386 | float %}
          {% set tn = 240.7263 | float %}
          {% set pwa = pw / A | float %}
          {{ tn / ( m / log(pwa,10) - 1) }}



        