- platform: file
  name: sauna_temperature
  file_path: custom_components/ruuvitag-sensor/tag1.json
  value_template: '{{ value_json.temperature }}'
  unit_of_measurement: "°C"
  scan_interval: 1

- platform: file
  name: sauna_humidity
  file_path: custom_components/ruuvitag-sensor/tag1.json
  value_template: '{{ value_json.humidity }}'
  unit_of_measurement: "%"
  scan_interval: 1

- platform: file
  name: sauna_pressure
  file_path: custom_components/ruuvitag-sensor/tag1.json
  value_template: '{{ value_json.pressure }}'
  unit_of_measurement: "hPa"
  scan_interval: 1