# IR - lähetin
- platform: broadlink
  host: 192.168.1.125
  mac: 78:0F:77:4F:80:C4

# TV-hallinta
- platform: template
  switches:
    tv:
      value_template: "{{ is_state('input_boolean.tv', 'on') }}"
      turn_on:
        - service: hdmi_cec.power_on
      turn_off:
        - service: hdmi_cec.standby