resources:
- type: js
  url: /local/card-mod/card-mod.js?v=1
- type: module
  url: /local/slider-entity-row/slider-entity-row.js?v=1
- type: js
  url: /local/vertical-stack-in-card/vertical-stack-in-card.js?v=0.1.3

views:
  - title: main
    icon: mdi:home-outline
    cards:
    - type: custom:vertical-stack-in-card # Olohuone yhdessä kortissa
      title: olohuone
      cards:
      - type: glance # olohuoneen pikavalinnat
        show_name: true
        show_state: false
        entities:
        - entity: script.livingroom_on
          name: päälle
          icon: mdi:lightbulb-on-outline
          tap_action:
            action: toggle
        - entity: script.morning
          name: aamu
          icon: mdi:weather-hazy
          tap_action:
            action: toggle        
        - entity: script.daytime
          name: päivä
          icon: mdi:weather-sunny
          tap_action:
            action: toggle        
        - entity: script.evening
          name: ilta
          icon: mdi:weather-sunset
          tap_action:
            action: toggle     
        - entity: script.movie
          name: elokuva
          icon: mdi:filmstrip
          tap_action:
            action: toggle     
        - entity: script.livingroom_off
          name: pois
          icon: mdi:lightbulb-off-outline
          tap_action:
            action: toggle     
      - type: entities # Olohuoneen tarkempi kontrolli
        entities:
          - type: custom:slider-entity-row
            entity: light.livingroom
            name: kirkkaus
            min: 1
            max: 100
            step: 1
            hide_when_off: true
          - type: custom:slider-entity-row
            entity: light.livingroom
            attribute: color_temp
            name: värilämpötila
            min: 250
            max: 454
            hide_when_off: true

    - type: custom:vertical-stack-in-card # Sauna
      title: sauna
      cards:
      - type: entities # Saunan lämpötilatiedot
        show_header_toggle: false
        entities:
        - entity: sensor.sauna_temperature
          icon: mdi:thermometer
          name: lämpötila
        - entity: sensor.sauna_humidity
          icon: mdi:water-percent
          name: suhteellinen kosteus
      - type: history-graph
        entities:
        - entity: sensor.sauna_temperature
          name: lämpötila

    - type: entities # ulkoilman lämpötilatiedot
      title: ulkoilma
      show_header_toggle: false
      entities:
      - entity: sensor.outside_temperature
        icon: mdi:thermometer
        name: lämpötila
      - entity: sensor.outside_humidity
        icon: mdi:water-percent
        name: suhteellinen kosteus
      - entity: sensor.outside_pressure
        icon: mdi:speedometer
        name: ilmanpaine
      - entity: sensor.outside_dewpoint
        icon: mdi:coolant-temperature
        name: kastepiste