views:
  - title: main
    icon: mdi:home-outline
    cards:
    - type: custom:vertical-stack-in-card # Olohuone yhdessä kortissa
      title: olohuone
      cards:
      - type: glance # olohuoneen pikavalinnat
        show_name: true
        show_state: false
        columns: 6
        entities:
        - entity: script.livingroom_on
          name: päälle
          icon: mdi:lightbulb-on-outline
          tap_action:
            action: toggle
        - entity: script.morning
          name: aamu
          icon: mdi:weather-hazy
          tap_action:
            action: toggle        
        - entity: script.daytime
          name: päivä
          icon: mdi:weather-sunny
          tap_action:
            action: toggle        
        - entity: script.evening
          name: ilta
          icon: mdi:weather-sunset
          tap_action:
            action: toggle     
        - entity: script.movie
          name: elokuva
          icon: mdi:filmstrip
          tap_action:
            action: toggle     
        - entity: script.livingroom_off
          name: pois
          icon: mdi:lightbulb-off-outline
          tap_action:
            action: toggle     
      - type: entities # Olohuoneen tarkempi kontrolli
        entities:
          - type: custom:slider-entity-row
            entity: light.livingroom
            name: kirkkaus
            min: 1
            max: 100
            step: 1
            hide_when_off: true
            full_row: true
            transition: 1
          - type: custom:slider-entity-row
            entity: light.livingroom
            attribute: color_temp
            name: värilämpötila
            min: 250
            max: 454
            hide_when_off: true
            full_row: true
            transition: 1
          - entity: switch.tv # Television virtakytkin
            name: televisio
            icon: mdi:television
          - entity: switch.tradfri_outlet_2 # Vahvistimen virtakytkin.
            name: äänentoisto
            icon: mdi:speaker
          - type: custom:slider-entity-row
            min: 0
            max: 100
            entity: cover.tradfri_blind
            name: verho
            icon: mdi-blinds
  
    - type: entities # Muut valot 
      title: muut valot
      show_header_toggle: false
      entities:
      - entity: light.tradfri_driver
        name: keittiö
      - type: custom:slider-entity-row
        entity: light.tradfri_driver
        min: 1
        max: 100
        step: 1
        hide_when_off: true
        full_row: true
        transition: 1
      - entity: switch.tradfri_outlet
        name: kirkasvalolamppu
      - entity: light.tradfri_bulb_5
        name: eteinen
  
    - type: entities # Makuuhuoneen kytkimet ja liukusäätimet
      title: makuuhuone
      show_header_toggle: false
      entities:
      - entity: light.bedroom
        name: kaikki valot
      - entity: light.bedroom
        type: custom:slider-entity-row
        name: kirkkaus
        min: 1
        max: 100
        step: 1
        hide_when_off: true
        transition: 1
        full_row: true
      - type: custom:slider-entity-row
        entity: light.bedroom
        attribute: color_temp
        name: värilämpötila
        min: 250
        max: 454
        hide_when_off: true
        transition: 1
        full_row: true
      - entity: light.tradfri_bulb_3
        name: kattovalo
      - entity: light.tradfri_bulb_4
        name: lukuvalo

    - type: custom:vertical-stack-in-card # Sauna
      title: sauna
      cards:
      - type: entities # Saunan lämpötilatiedot
        show_header_toggle: false
        entities:
        - entity: sensor.sauna_temperature
          icon: mdi:thermometer
          name: lämpötila
        - entity: sensor.sauna_humidity
          icon: mdi:water-percent
          name: suhteellinen kosteus
      - type: history-graph # Graafi
        refresh_interval: 30
        entities:
        - entity: sensor.sauna_temperature
          name: lämpötila


    - type: custom:vertical-stack-in-card # ulkoilman lämpötilatiedot
      title: ulkoilma
      cards:
      - type: entities # Numeeriset tiedot
        show_header_toggle: false
        entities:
        - entity: sensor.outside_temperature
          icon: mdi:thermometer
          name: lämpötila
        - entity: sensor.outside_humidity
          icon: mdi:water-percent
          name: suhteellinen kosteus
        - entity: sensor.outside_pressure
          icon: mdi:speedometer
          name: ilmanpaine
        - entity: sensor.outside_dewpoint
          icon: mdi:coolant-temperature
          name: kastepiste
      - type: history-graph # graafi
        refresh_interval: 30
        entities:
        - entity: sensor.outside_temperature
          name: lämpötila
        - entity: sensor.outside_dewpoint
          name: kastepiste

    - type: custom:vertical-stack-in-card # sisäilman lämpötilatiedot
      title: sisäilma
      cards:
      - type: entities # Numeeriset tiedot
        show_header_toggle: false
        entities:
        - entity: sensor.inside_temperature
          icon: mdi:thermometer
          name: lämpötila
        - entity: sensor.inside_humidity
          icon: mdi:water-percent
          name: suhteellinen kosteus
        - entity: sensor.inside_pressure
          icon: mdi:speedometer
          name: ilmanpaine
        - entity: sensor.inside_dewpoint
          icon: mdi:coolant-temperature
          name: kastepiste
      - type: history-graph # graafi
        refresh_interval: 30
        entities:
        - entity: sensor.inside_temperature
          name: lämpötila
        - entity: sensor.inside_dewpoint
          name: kastepiste